# coding: utf-8

"""
    PostgREST API

    standard public schema  # noqa: E501

    OpenAPI spec version: 0.5.0.0 (d8896be)
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api._rpc_login_api import RpcLoginApi  # noqa: E501
from swagger_client.rest import ApiException


class TestRpcLoginApi(unittest.TestCase):
    """RpcLoginApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api._rpc_login_api.RpcLoginApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_rpc_login_post(self):
        """Test case for rpc_login_post

        """
        pass


if __name__ == '__main__':
    unittest.main()
