# coding: utf-8

"""
    PostgREST API

    standard public schema  # noqa: E501

    OpenAPI spec version: 0.5.0.0 (d8896be)
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.addrs import Addrs  # noqa: E501
from swagger_client.rest import ApiException


class TestAddrs(unittest.TestCase):
    """Addrs unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAddrs(self):
        """Test Addrs"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.addrs.Addrs()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
