# coding: utf-8

"""
    PostgREST API

    standard public schema  # noqa: E501

    OpenAPI spec version: 0.5.0.0 (d8896be)
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.introspection_api import IntrospectionApi  # noqa: E501
from swagger_client.rest import ApiException


class TestIntrospectionApi(unittest.TestCase):
    """IntrospectionApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.introspection_api.IntrospectionApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_root_get(self):
        """Test case for root_get

        OpenAPI description (this document)  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
