# coding: utf-8

"""
    PostgREST API

    standard public schema  # noqa: E501

    OpenAPI spec version: 0.5.0.0 (d8896be)
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.blocks_api import BlocksApi  # noqa: E501
from swagger_client.rest import ApiException


class TestBlocksApi(unittest.TestCase):
    """BlocksApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.blocks_api.BlocksApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_blocks_delete(self):
        """Test case for blocks_delete

        """
        pass

    def test_blocks_get(self):
        """Test case for blocks_get

        """
        pass

    def test_blocks_patch(self):
        """Test case for blocks_patch

        """
        pass

    def test_blocks_post(self):
        """Test case for blocks_post

        """
        pass


if __name__ == '__main__':
    unittest.main()
