# coding: utf-8

"""
    PostgREST API

    standard public schema  # noqa: E501

    OpenAPI spec version: 0.5.0.0 (d8896be)
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.addrs_api import AddrsApi  # noqa: E501
from swagger_client.rest import ApiException


class TestAddrsApi(unittest.TestCase):
    """AddrsApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.addrs_api.AddrsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_addrs_delete(self):
        """Test case for addrs_delete

        """
        pass

    def test_addrs_get(self):
        """Test case for addrs_get

        """
        pass

    def test_addrs_patch(self):
        """Test case for addrs_patch

        """
        pass

    def test_addrs_post(self):
        """Test case for addrs_post

        """
        pass


if __name__ == '__main__':
    unittest.main()
