# coding: utf-8

"""
    PostgREST API

    standard public schema  # noqa: E501

    OpenAPI spec version: 0.5.0.0 (d8896be)
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.contracts_api import ContractsApi  # noqa: E501
from swagger_client.rest import ApiException


class TestContractsApi(unittest.TestCase):
    """ContractsApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.contracts_api.ContractsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_contracts_delete(self):
        """Test case for contracts_delete

        """
        pass

    def test_contracts_get(self):
        """Test case for contracts_get

        """
        pass

    def test_contracts_patch(self):
        """Test case for contracts_patch

        """
        pass

    def test_contracts_post(self):
        """Test case for contracts_post

        """
        pass


if __name__ == '__main__':
    unittest.main()
