# coding: utf-8

"""
    PostgREST API

    standard public schema  # noqa: E501

    OpenAPI spec version: 0.5.0.0 (d8896be)
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api._rpc_update_users_api import RpcUpdateUsersApi  # noqa: E501
from swagger_client.rest import ApiException


class TestRpcUpdateUsersApi(unittest.TestCase):
    """RpcUpdateUsersApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api._rpc_update_users_api.RpcUpdateUsersApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_rpc_update_users_post(self):
        """Test case for rpc_update_users_post

        """
        pass


if __name__ == '__main__':
    unittest.main()
