# coding: utf-8

"""
    PostgREST API

    standard public schema  # noqa: E501

    OpenAPI spec version: 0.5.0.0 (d8896be)
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api._rpc_dearmor_api import RpcDearmorApi  # noqa: E501
from swagger_client.rest import ApiException


class TestRpcDearmorApi(unittest.TestCase):
    """RpcDearmorApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api._rpc_dearmor_api.RpcDearmorApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_rpc_dearmor_post(self):
        """Test case for rpc_dearmor_post

        """
        pass


if __name__ == '__main__':
    unittest.main()
