/**
 * PostgREST API
 * standard public schema
 *
 * OpenAPI spec version: 0.5.0.0 (d8896be)
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: unset
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.PostgRestApi);
  }
}(this, function(expect, PostgRestApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new PostgRestApi.Contracts();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('Contracts', function() {
    it('should create an instance of Contracts', function() {
      // uncomment below and update the code to test Contracts
      //var instane = new PostgRestApi.Contracts();
      //expect(instance).to.be.a(PostgRestApi.Contracts);
    });

    it('should have the property addr (base name: "addr")', function() {
      // uncomment below and update the code to test the property addr
      //var instane = new PostgRestApi.Contracts();
      //expect(instance).to.be();
    });

    it('should have the property bytecode (base name: "bytecode")', function() {
      // uncomment below and update the code to test the property bytecode
      //var instane = new PostgRestApi.Contracts();
      //expect(instance).to.be();
    });

    it('should have the property balance (base name: "balance")', function() {
      // uncomment below and update the code to test the property balance
      //var instane = new PostgRestApi.Contracts();
      //expect(instance).to.be();
    });

  });

}));
