/**
 * PostgREST API
 * standard public schema
 *
 * OpenAPI spec version: 0.5.0.0 (d8896be)
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: unset
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.PostgRestApi) {
      root.PostgRestApi = {};
    }
    root.PostgRestApi.Args = factory(root.PostgRestApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The Args model module.
   * @module model/Args
   * @version 0.5.0.0 (d8896be)
   */

  /**
   * Constructs a new <code>Args</code>.
   * @alias module:model/Args
   * @class
   * @param email {String} 
   * @param token {String} 
   * @param pass {String} 
   */
  var exports = function(email, token, pass) {
    var _this = this;

    _this['email'] = email;
    _this['token'] = token;
    _this['pass'] = pass;
  };

  /**
   * Constructs a <code>Args</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Args} obj Optional instance to populate.
   * @return {module:model/Args} The populated <code>Args</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('email')) {
        obj['email'] = ApiClient.convertToType(data['email'], 'String');
      }
      if (data.hasOwnProperty('token')) {
        obj['token'] = ApiClient.convertToType(data['token'], 'String');
      }
      if (data.hasOwnProperty('pass')) {
        obj['pass'] = ApiClient.convertToType(data['pass'], 'String');
      }
    }
    return obj;
  }

  /**
   * @member {String} email
   */
  exports.prototype['email'] = undefined;
  /**
   * @member {String} token
   */
  exports.prototype['token'] = undefined;
  /**
   * @member {String} pass
   */
  exports.prototype['pass'] = undefined;



  return exports;
}));


