/**
 * PostgREST API
 * standard public schema
 *
 * OpenAPI spec version: 0.5.0.0 (d8896be)
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: unset
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/Addrs'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('../model/Addrs'));
  } else {
    // Browser globals (root is window)
    if (!root.PostgRestApi) {
      root.PostgRestApi = {};
    }
    root.PostgRestApi.AddrsApi = factory(root.PostgRestApi.ApiClient, root.PostgRestApi.Addrs);
  }
}(this, function(ApiClient, Addrs) {
  'use strict';

  /**
   * Addrs service.
   * @module api/AddrsApi
   * @version 0.5.0.0 (d8896be)
   */

  /**
   * Constructs a new AddrsApi. 
   * @alias module:api/AddrsApi
   * @class
   * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
   * default to {@link module:ApiClient#instance} if unspecified.
   */
  var exports = function(apiClient) {
    this.apiClient = apiClient || ApiClient.instance;


    /**
     * Callback function to receive the result of the addrsDelete operation.
     * @callback module:api/AddrsApi~addrsDeleteCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * @param {Object} opts Optional parameters
     * @param {String} opts.addr 
     * @param {String} opts.balance 
     * @param {module:model/String} opts.prefer Preference
     * @param {module:api/AddrsApi~addrsDeleteCallback} callback The callback function, accepting three arguments: error, data, response
     */
    this.addrsDelete = function(opts, callback) {
      opts = opts || {};
      var postBody = null;


      var pathParams = {
      };
      var queryParams = {
        'addr': opts['addr'],
        'balance': opts['balance'],
      };
      var collectionQueryParams = {
      };
      var headerParams = {
        'Prefer': opts['prefer']
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = ['application/json', 'application/vnd.pgrst.object+json', 'text/csv'];
      var accepts = ['application/json', 'application/vnd.pgrst.object+json', 'text/csv'];
      var returnType = null;

      return this.apiClient.callApi(
        '/addrs', 'DELETE',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the addrsGet operation.
     * @callback module:api/AddrsApi~addrsGetCallback
     * @param {String} error Error message, if any.
     * @param {module:model/Addrs} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * @param {Object} opts Optional parameters
     * @param {String} opts.addr 
     * @param {String} opts.balance 
     * @param {String} opts.select Filtering Columns
     * @param {String} opts.order Ordering
     * @param {String} opts.range Limiting and Pagination
     * @param {String} opts.rangeUnit Limiting and Pagination (default to items)
     * @param {String} opts.offset Limiting and Pagination
     * @param {String} opts.limit Limiting and Pagination
     * @param {module:model/String} opts.prefer Preference
     * @param {module:api/AddrsApi~addrsGetCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/Addrs}
     */
    this.addrsGet = function(opts, callback) {
      opts = opts || {};
      var postBody = null;


      var pathParams = {
      };
      var queryParams = {
        'addr': opts['addr'],
        'balance': opts['balance'],
        'select': opts['select'],
        'order': opts['order'],
        'offset': opts['offset'],
        'limit': opts['limit'],
      };
      var collectionQueryParams = {
      };
      var headerParams = {
        'Range': opts['range'],
        'Range-Unit': opts['rangeUnit'],
        'Prefer': opts['prefer']
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = ['application/json', 'application/vnd.pgrst.object+json', 'text/csv'];
      var accepts = ['application/json', 'application/vnd.pgrst.object+json', 'text/csv'];
      var returnType = Addrs;

      return this.apiClient.callApi(
        '/addrs', 'GET',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the addrsPatch operation.
     * @callback module:api/AddrsApi~addrsPatchCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * @param {Object} opts Optional parameters
     * @param {String} opts.addr 
     * @param {String} opts.balance 
     * @param {module:model/Addrs} opts.addrs addrs
     * @param {module:model/String} opts.prefer Preference
     * @param {module:api/AddrsApi~addrsPatchCallback} callback The callback function, accepting three arguments: error, data, response
     */
    this.addrsPatch = function(opts, callback) {
      opts = opts || {};
      var postBody = opts['addrs'];


      var pathParams = {
      };
      var queryParams = {
        'addr': opts['addr'],
        'balance': opts['balance'],
      };
      var collectionQueryParams = {
      };
      var headerParams = {
        'Prefer': opts['prefer']
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = ['application/json', 'application/vnd.pgrst.object+json', 'text/csv'];
      var accepts = ['application/json', 'application/vnd.pgrst.object+json', 'text/csv'];
      var returnType = null;

      return this.apiClient.callApi(
        '/addrs', 'PATCH',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the addrsPost operation.
     * @callback module:api/AddrsApi~addrsPostCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * @param {Object} opts Optional parameters
     * @param {module:model/Addrs} opts.addrs addrs
     * @param {module:model/String} opts.prefer Preference
     * @param {module:api/AddrsApi~addrsPostCallback} callback The callback function, accepting three arguments: error, data, response
     */
    this.addrsPost = function(opts, callback) {
      opts = opts || {};
      var postBody = opts['addrs'];


      var pathParams = {
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
        'Prefer': opts['prefer']
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = ['application/json', 'application/vnd.pgrst.object+json', 'text/csv'];
      var accepts = ['application/json', 'application/vnd.pgrst.object+json', 'text/csv'];
      var returnType = null;

      return this.apiClient.callApi(
        '/addrs', 'POST',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
  };

  return exports;
}));
