=begin
#PostgREST API

#standard public schema

OpenAPI spec version: 0.5.0.0 (d8896be)

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: unset

=end

require 'spec_helper'
require 'json'

# Unit tests for SwaggerClient::IntrospectionApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'IntrospectionApi' do
  before do
    # run before each test
    @instance = SwaggerClient::IntrospectionApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of IntrospectionApi' do
    it 'should create an instance of IntrospectionApi' do
      expect(@instance).to be_instance_of(SwaggerClient::IntrospectionApi)
    end
  end

  # unit tests for root_get
  # OpenAPI description (this document)
  # 
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'root_get test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
