=begin
#PostgREST API

#standard public schema

OpenAPI spec version: 0.5.0.0 (d8896be)

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: unset

=end

require 'spec_helper'
require 'json'

# Unit tests for SwaggerClient::AddrsApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'AddrsApi' do
  before do
    # run before each test
    @instance = SwaggerClient::AddrsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of AddrsApi' do
    it 'should create an instance of AddrsApi' do
      expect(@instance).to be_instance_of(SwaggerClient::AddrsApi)
    end
  end

  # unit tests for addrs_delete
  # 
  # 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :addr 
  # @option opts [String] :balance 
  # @option opts [String] :prefer Preference
  # @return [nil]
  describe 'addrs_delete test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for addrs_get
  # 
  # 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :addr 
  # @option opts [String] :balance 
  # @option opts [String] :select Filtering Columns
  # @option opts [String] :order Ordering
  # @option opts [String] :range Limiting and Pagination
  # @option opts [String] :range_unit Limiting and Pagination
  # @option opts [String] :offset Limiting and Pagination
  # @option opts [String] :limit Limiting and Pagination
  # @option opts [String] :prefer Preference
  # @return [Addrs]
  describe 'addrs_get test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for addrs_patch
  # 
  # 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :addr 
  # @option opts [String] :balance 
  # @option opts [Addrs] :addrs addrs
  # @option opts [String] :prefer Preference
  # @return [nil]
  describe 'addrs_patch test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for addrs_post
  # 
  # 
  # @param [Hash] opts the optional parameters
  # @option opts [Addrs] :addrs addrs
  # @option opts [String] :prefer Preference
  # @return [nil]
  describe 'addrs_post test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
