=begin
#PostgREST API

#standard public schema

OpenAPI spec version: 0.5.0.0 (d8896be)

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: unset

=end

require 'spec_helper'
require 'json'

# Unit tests for SwaggerClient::ContractsApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'ContractsApi' do
  before do
    # run before each test
    @instance = SwaggerClient::ContractsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of ContractsApi' do
    it 'should create an instance of ContractsApi' do
      expect(@instance).to be_instance_of(SwaggerClient::ContractsApi)
    end
  end

  # unit tests for contracts_delete
  # 
  # 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :addr 
  # @option opts [String] :bytecode 
  # @option opts [String] :balance 
  # @option opts [String] :prefer Preference
  # @return [nil]
  describe 'contracts_delete test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for contracts_get
  # 
  # 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :addr 
  # @option opts [String] :bytecode 
  # @option opts [String] :balance 
  # @option opts [String] :select Filtering Columns
  # @option opts [String] :order Ordering
  # @option opts [String] :range Limiting and Pagination
  # @option opts [String] :range_unit Limiting and Pagination
  # @option opts [String] :offset Limiting and Pagination
  # @option opts [String] :limit Limiting and Pagination
  # @option opts [String] :prefer Preference
  # @return [Contracts]
  describe 'contracts_get test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for contracts_patch
  # 
  # 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :addr 
  # @option opts [String] :bytecode 
  # @option opts [String] :balance 
  # @option opts [Contracts] :contracts contracts
  # @option opts [String] :prefer Preference
  # @return [nil]
  describe 'contracts_patch test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for contracts_post
  # 
  # 
  # @param [Hash] opts the optional parameters
  # @option opts [Contracts] :contracts contracts
  # @option opts [String] :prefer Preference
  # @return [nil]
  describe 'contracts_post test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
