/*
 * PostgREST API
 *
 * standard public schema
 *
 * API version: 0.5.0.0 (d8896be)
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type Addrs struct {

	// Note: This is a Primary Key.<pk/>
	Addr string `json:"addr,omitempty"`

	Balance float32 `json:"balance,omitempty"`
}
