/*
 * PostgREST API
 *
 * standard public schema
 *
 * API version: 0.5.0.0 (d8896be)
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type Args2 struct {

	Email string `json:"email"`
}
