/*
 * PostgREST API
 *
 * standard public schema
 *
 * API version: 0.5.0.0 (d8896be)
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type Blocks struct {

	// Note: This is a Primary Key.<pk/>
	Block int32 `json:"block,omitempty"`
}
