# coding: utf-8

# flake8: noqa
"""
    PostgREST API

    standard public schema  # noqa: E501

    OpenAPI spec version: 0.5.0.0 (d8896be)
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

# import models into model package
from swagger_client.models.addrs import Addrs
from swagger_client.models.blocks import Blocks
from swagger_client.models.contracts import Contracts
