# coding: utf-8

# flake8: noqa
"""
    PostgREST API

    standard public schema  # noqa: E501

    OpenAPI spec version: 0.5.0.0 (d8896be)
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

# import models into model package
from swagger_client.models.args import Args
from swagger_client.models.args_1 import Args1
from swagger_client.models.args_2 import Args2
from swagger_client.models.args_3 import Args3
